import type { Metadata } from "next";
import { Orbitron ,Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./Provider";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400",'500','600', "700","800", "900"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${orbitron.variable} ${inter.variable} antialiased`}
      >
        <ThemeProvider  attribute="class"
          defaultTheme="dark"
          enableSystem={true}
          storageKey="theme"
          disableTransitionOnChange > 
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
